name: tsar_wars
description: "In the darkest of times, a hero will always appear."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.0.0
  equatable: ^2.0.5
  flame: ^1.18.0
  flame_audio: ^2.10.2
  flutter_bloc: ^8.1.6
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  hydrated_bloc: ^9.1.5
  logging: ^1.2.0
  nes_ui: ^0.20.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flame_test: ^1.16.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  test: ^1.25.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/dash/
    - assets/images/enemies/
    - assets/images/jedai/
    - assets/images/scenery/
    - assets/music/
    - assets/sfx/
    
  fonts:
    - family: Press Start 2P
      fonts:
        - asset: assets/fonts/Press_Start_2P/PressStart2P-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  remove_alpha_ios: true